jwt:
  secret: aslkjasdhfkahsfashjdfkashfdkajshdfkjshfdashflkhasfdhaskdfjhaskdjfhsahasdfasdfasdfslkjhlkjh
server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: java
    password: javapassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG